,vm-init-start implemented

diff --git a/bin/actor b/bin/actor
--- a/bin/actor
+++ b/bin/actor
@@ -4,12 +4,31 @@ IFS=$'\n\t'
 
 MSG="${0##*/}"
 
+function inside_container_check() {
+  if [[ ! -v GUIX_ENVIRONMENT ]]; then
+    echo "ERROR | should be inside the container"
+    exit 1
+  fi
+}
+
+function outside_container_check() {
+  if [[ -v GUIX_ENVIRONMENT ]]; then
+    echo "ERROR | should be outside the container"
+    exit 1
+  fi
+}
+
 if [[ "$MSG" == ",install-node-binaries" ]]; then
   # [[ref:220179a9-aa3e-490d-ab6e-3ef02d759bee][Specification]]
+
+  inside_container_check
   npm install -g bash-language-server
 
 elif [[ "$MSG" == ",frontend-fetch" ]]; then
   # [[ref:c6dfad7d-72df-4788-ac6f-97c297f6df94][Specification]]
+
+  inside_container_check
+
   URL="$1"
   SERVER="$2"
   # TODO(c783): take into account the fact that URL may change
@@ -24,6 +43,9 @@ elif [[ "$MSG" == ",frontend-fetch" ]]; then
 
 elif [[ "$MSG" == ",db-start" ]]; then
   # [[ref:01add4d6-2dca-4100-a17a-b947ad5b25ca][Specification]]
+
+  inside_container_check
+
   mkdir -p "$DB_RUN"
   chmod 700 "$DB_RUN"
 
@@ -51,6 +73,9 @@ EOF
 
 elif [[ "$MSG" == ",backend-iex-start" ]]; then
   # [[ref:56e0e558-5ea0-4ca3-9f75-0129149aa702][Specification]]
+
+  inside_container_check
+
   cd "$BACKEND"
 
   ,db-start
@@ -68,9 +93,72 @@ elif [[ "$MSG" == ",backend-iex-start" ]]; then
 
 elif [[ "$MSG" == ",app-start" ]]; then
   # [[ref:3a2b4174-ea2e-4ed2-97b3-23b562be59a2][Specification]]
+
+  inside_container_check
+
   URL="$1"
   ,frontend-fetch "$URL" "$BACKEND_URL"
   ,backend-iex-start
+
+elif [[ "$MSG" == ",image-init-build" ]]; then
+  # [[ref:ead19c86-d75c-45d6-8aa7-00cea2f049b0][Specification]]
+
+  inside_container_check
+
+  IMG_PATH="$(guix time-machine -C "$CHANNELS" -- system image -t qcow2 --image-size=20G "$OS_INIT")"
+  # TODO(1ce3): maybe compare hashes if existance to save time?
+  cp -f "$IMG_PATH" "$IMAGE_INIT"
+  chmod +w "$IMAGE_INIT"
+
+elif [[ "$MSG" == ",vm-init-start" ]]; then
+  # [[ref:518d54c7-3288-4b71-a951-e612dfab5cb2][Specification]]
+
+  outside_container_check
+
+  ROOT="$(git rev-parse --show-toplevel)"
+  source "$ROOT/etc/bash-dev-profile"
+
+  if [[ ! -e "$IMAGE_INIT" ]]; then
+    echo "ERROR | Execute ,image-init-build within the container first"
+    exit 1
+  fi
+
+  # [[ref:9952e0a0-6fe0-40cb-97fd-1d56074ab2a5][Specification]]
+  mkdir -p "$VM_RUN"
+  systemctl --user stop "$VM_UNIT" 2>/dev/null || true
+  systemctl --user reset-failed "$VM_UNIT" 2>/dev/null || true
+  systemd-run --user --unit="$VM_UNIT" --collect -- \
+    qemu-system-x86_64 \
+    -machine type=q35,accel=kvm \
+    -cpu host -m 8192 -smp cores=4 \
+    -snapshot \
+    -blockdev driver=qcow2,node-name=disk0,file.driver=file,file.filename="$IMAGE_INIT" \
+    -device virtio-blk-pci,drive=disk0 \
+    -netdev user,id=net0,hostfwd=tcp::"$VM_PORT_SSH"-:22,hostfwd=tcp::"$VM_PORT_HTTP"-:80,hostfwd=tcp::"$VM_PORT_HTTPS"-:443 \
+    -device virtio-net-pci,netdev=net0 \
+    -chardev socket,id=mon,path="$VM_SOCKET",server=on,wait=off \
+    -mon chardev=mon,mode=control
+
+  systemctl --user --no-pager status "$VM_UNIT"
+
+  echo "INFO | Waiting for VM sshd..."
+  for i in $(seq 1 20); do
+    echo "INFO | Attempt $i"
+    ssh-keyscan -p "$VM_PORT_SSH" -T 1 127.0.0.1 2>/dev/null | grep -q ssh && break
+    sleep 1
+    if [[ $i -eq 20 ]]; then
+      echo "ERROR | VM sshd did not start within 20 seconds" >&2
+      exit 1
+    fi
+  done
+
+  ssh -p "$VM_PORT_SSH" -i "$KEY_SSH_PUB" \
+    -o StrictHostKeyChecking=no \
+    -o UserKnownHostsFile=/dev/null \
+    root@localhost
+
+elif [[ "$MSG" == ",vm-deploy" ]]; then
+  echo "$MSG" "$@"
 
 else
   echo "Unexpected message: $MSG"
